export enum ProductsActionTypes {
  PRODUCTS_FETCH_REQUEST = 'PRODUCTS_FETCH_REQUEST',
  PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCESS',
  PRODUCTS_FETCH_FAIL = 'PRODUCST_FETCH_FAIL',
  PRODUCTS_RESET = 'PRODUCTS_RESET',
}
