export enum SingleProductActionTypes {
  SINGLE_PRODUCT_FETCH_REQUEST = 'SINGLE_PRODUCT_FETCH_REQUEST',
  SINGLE_PRODUCT_FETCH_SUCESS = 'SINGLE_PRODUCT_FETCH_SUCCESS',
  SINGLE_PRODUCT_FETCH_FAIL = 'SINGLE_PRODUCT_FETCH_FAIL',
  SINGLE_PRODUCT_RESET = 'SINGLE_PRODUCT_RESET',
}
